/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;
import javax.swing.JOptionPane;

/**
 *
 * @author lushi
 */
public class frmDepositoMonedaTipo extends javax.swing.JFrame {

    /**
     * Creates new form frmDepositoMonedaTipo
     */
    public frmDepositoMonedaTipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValorRecolectado = new javax.swing.JTextField();
        txtNumMonedas = new javax.swing.JTextField();
        txtDenominacion = new javax.swing.JTextField();
        btnLeer = new javax.swing.JButton();
        btnEscribir = new javax.swing.JButton();
        btnMetodo1 = new javax.swing.JButton();
        btnMetodo2 = new javax.swing.JButton();
        btnMetodo3 = new javax.swing.JButton();
        btnMetodo4 = new javax.swing.JButton();
        btnMetodo5 = new javax.swing.JButton();
        btnMetodo6 = new javax.swing.JButton();
        btnMetodo7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtValorRecolectado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorRecolectadoActionPerformed(evt);
            }
        });

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnEscribir.setText("Escribir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        btnMetodo1.setText("Metodo 1");
        btnMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo1ActionPerformed(evt);
            }
        });

        btnMetodo2.setText("Metodo 2");
        btnMetodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo2ActionPerformed(evt);
            }
        });

        btnMetodo3.setText("Metodo 3 ");
        btnMetodo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo3ActionPerformed(evt);
            }
        });

        btnMetodo4.setText("Metodo 4");
        btnMetodo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo4ActionPerformed(evt);
            }
        });

        btnMetodo5.setText("Metodo 5");
        btnMetodo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo5ActionPerformed(evt);
            }
        });

        btnMetodo6.setText("Metoo 6");
        btnMetodo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo6ActionPerformed(evt);
            }
        });

        btnMetodo7.setText("Metodo 7");
        btnMetodo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor  Recolectado");

        jLabel2.setText("Numero de Monedas");

        jLabel3.setText("Denominacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel3)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnLeer)
                        .addGap(46, 46, 46)
                        .addComponent(btnEscribir)))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMetodo4)
                    .addComponent(btnMetodo3)
                    .addComponent(btnMetodo2)
                    .addComponent(btnMetodo1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnMetodo6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMetodo7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMetodo5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMetodo1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnMetodo3)
                        .addGap(13, 13, 13)
                        .addComponent(btnMetodo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMetodo5)
                        .addGap(18, 18, 18)
                        .addComponent(btnMetodo6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtValorRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMetodo2)
                                .addComponent(jLabel1)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLeer)
                            .addComponent(btnEscribir))))
                .addGap(18, 18, 18)
                .addComponent(btnMetodo7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // INSTANCIAR LA CLASE  ALUMNO
    CapaNegocio.DepositoMonedaTipo depositoMonedaTipo = new CapaNegocio.DepositoMonedaTipo();
    private void txtValorRecolectadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorRecolectadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorRecolectadoActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // TODO add your handling code here:
         //leer el contenido dde las cajas  de texto
    String  valorRecolectado = txtValorRecolectado.getText();
    String numMonedas = txtNumMonedas.getText();
    String denominacion = txtDenominacion.getText();
    
    //llevar los datos a los atributos del objeto a traves de las propiedades
    depositoMonedaTipo.setValorRecolectado(valorRecolectado);
    depositoMonedaTipo.setNumMonedas(numMonedas);
    depositoMonedaTipo.setDenominacion(denominacion);
   
    //mostrar el mensaje 
    JOptionPane.showMessageDialog(rootPane, "Datos registrados en el objeto");
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(rootPane, 
                "Valor Recolectao: " + depositoMonedaTipo.getValorRecolectado() + "\n" +
                "Numero de monedas: " +depositoMonedaTipo.getNumMonedas()+"\n" +
                 "Denominacion: " + depositoMonedaTipo.getDenominacion() );
    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(rootPane,String.valueOf( depositoMonedaTipo.RecibirMoneda().toString()));
    }//GEN-LAST:event_btnMetodo1ActionPerformed

    private void btnMetodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo2ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(rootPane,String.valueOf( depositoMonedaTipo.CancelarOperacion().toString()));
    }//GEN-LAST:event_btnMetodo2ActionPerformed

    private void btnMetodo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo3ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(rootPane,String.valueOf( depositoMonedaTipo.ServirProducto().toString()));
    }//GEN-LAST:event_btnMetodo3ActionPerformed

    private void btnMetodo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo4ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(rootPane,String.valueOf( depositoMonedaTipo.Entregarvuelto().toString()));
    }//GEN-LAST:event_btnMetodo4ActionPerformed

    private void btnMetodo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo5ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(rootPane,String.valueOf( depositoMonedaTipo.AgregarMoneda().toString()));
    }//GEN-LAST:event_btnMetodo5ActionPerformed

    private void btnMetodo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(rootPane,String.valueOf( depositoMonedaTipo.VerificarMoneda().toString()));
    }//GEN-LAST:event_btnMetodo6ActionPerformed

    private void btnMetodo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(rootPane,String.valueOf( depositoMonedaTipo.DevolverMoneda().toString()));
    }//GEN-LAST:event_btnMetodo7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDepositoMonedaTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDepositoMonedaTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDepositoMonedaTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDepositoMonedaTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDepositoMonedaTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnMetodo1;
    private javax.swing.JButton btnMetodo2;
    private javax.swing.JButton btnMetodo3;
    private javax.swing.JButton btnMetodo4;
    private javax.swing.JButton btnMetodo5;
    private javax.swing.JButton btnMetodo6;
    private javax.swing.JButton btnMetodo7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDenominacion;
    private javax.swing.JTextField txtNumMonedas;
    private javax.swing.JTextField txtValorRecolectado;
    // End of variables declaration//GEN-END:variables
}
